image: node:10

pages:
  stage: deploy
  # before_script:
  # - apt-get update
  # - apt-get install -qq --no-install-recommends unzip
  script:
  - npm install
  - npm install gatsby-cli
  - node_modules/.bin/gatsby build --prefix-paths
  # - mkdir -p vf
  # - cd vf
  # - wget https://gitlab.com/zeropaper/fiha/-/jobs/artifacts/master/download?job=pages -O artifacts.zip
  # - unzip artifacts.zip
  # - ls -ashl public/
  # - rm public/index.html
  # - rm public/index.*.*
  # - cd ..
  # - cp -rf vf/public/* public/
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
  only:
    - master
